name: data-api-dist
include:
    - ./docker/compose.deps.yml
services:
    api:
        build: .
        ports:
            - '9080:8080'
        env_file:
            - ./docker/env/api.env
        environment:
            GIN_MODE: release
        depends_on:
            - hydra
            - redis
            - database
            - nats
