# @name createUser
POST http://localhost:8080/api/users
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@localhost.test",
  "foo": "bar"
}

###

GET http://localhost:8080/api/users/{{createUser.response.body.$.id}}
Content-Type: application/json
