name: data-api-devcontainer
include:
    - ./compose.deps.yml
services:
    devcontainer:
        build:
            context: ./images/devcontainer
            args:
                GO_VERSION: 1.24
        tty: true
        volumes:
            - ../:/workspace:cached
            - go-cache:/root/.cache
            - go-modules:/go/pkg/mod
        working_dir: /workspace
        env_file:
            - ./env/api.env
        networks:
            default:
                aliases:
                    - app.localhost

    nats-nui:
        image: ghcr.io/nats-nui/nui:latest
        ports:
            - '8089:31311'
        volumes:
            - nats-nui-data:/db

    redis-insight:
        image: redis/redisinsight:latest
        ports:
            - '8090:5540'
        environment:
            - RI_REDIS_HOST=redis

volumes:
    go-cache:
    go-modules:
    nats-nui-data:
