services:
    nats:
        image: nats:2.11-alpine
        ports:
            - '8087:4222'
            - '8088:8222'
        volumes:
            - nats-data:/data
        command: ['-js', '--store_dir', '/data']

    redis:
        image: redis:7-alpine

    postgresql:
        image: postgres:17-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: data_api
        volumes:
            - pg-data:/var/lib/postgresql/data
            - ./images/postgresql/init:/docker-entrypoint-initdb.d

    hydra-migrate:
        image: oryd/hydra:latest
        depends_on:
            - postgresql
        env_file:
            - ./env/hydra.env
        command: migrate sql -e --yes
        extra_hosts:
            - host.docker.internal:host-gateway

    hydra:
        image: oryd/hydra:latest
        depends_on:
            - hydra-migrate
        ports:
            - '4444:4444'
            - '4445:4445'
        env_file:
            - ./env/hydra.env
        command: serve all --dev
        networks:
            default:
                aliases:
                    - hydra.localhost

volumes:
    nats-data:
    pg-data:
