import type {Metadata} from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Data-API UI',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className='text-zinc-950 antialiased lg:bg-zinc-100 dark:bg-zinc-900 dark:text-white dark:lg:bg-zinc-950'
        >
            <head>
                <link rel='preconnect' href='https://rsms.me/' />
                <link rel='stylesheet' href='https://rsms.me/inter/inter.css' />
            </head>
            <body>{children}</body>
        </html>
    );
}
